root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

plugins:
  - search-pro
  - page-toc
  - code
  - mermaid
  - katex
  - hints
  - expandable-chapters
  - github
  - edit-link
  - analytics
  - sitemap
  - canonical-link
  - meta
  - favicon
  - theme-api

pluginsConfig:
  github:
    url: https://github.com/bondmcp/mcp
  edit-link:
    base: https://github.com/bondmcp/mcp/edit/main
    label: Edit This Page
  analytics:
    google: UA-XXXXXXXX-X
  sitemap:
    hostname: https://www.bondmcp.com
  meta:
    data:
      - name: description
        content: BondMCP Health AI Platform - Complete AI-powered healthcare platform with advanced health insights, medical research, and clinical decision support.
      - name: keywords
        content: health AI, medical AI, healthcare platform, clinical decision support, health insights, medical research
      - property: og:title
        content: BondMCP Health AI Platform
      - property: og:description
        content: Complete AI-powered healthcare platform with advanced health insights and clinical decision support
      - property: og:image
        content: https://www.bondmcp.com/assets/bondmcp-og-image.png
  favicon:
    shortcut: assets/favicon.ico
    bookmark: assets/favicon.ico
    appleTouch: assets/apple-touch-icon.png
    appleTouchMore:
      120x120: assets/apple-touch-icon-120x120.png
      180x180: assets/apple-touch-icon-180x180.png

pdf:
  fontSize: 12
  footerTemplate: '<div style="text-align:center;"><span class="pageNumber"></span></div>'
  headerTemplate: '<div style="text-align:center;">BondMCP Health AI Platform Documentation</div>'
  margin:
    top: 56
    bottom: 56
    right: 62
    left: 62
  pageNumbers: true
  paperSize: a4
