root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

variables:
  api_url: https://api.bondmcp.com/prod
  app_url: https://app.bondmcp.com
  status: LIVE
  version: 2.0.0-comprehensive
  endpoints: 52

integrations:
  openapi:
    - url: https://api.bondmcp.com/prod/openapi.json
      name: BondMCP API
