[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bondmcp_cli"
version = "0.1.0"
description = "CLI for interacting with the BondMCP public API"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=8.0",
    "requests>=2.25",
    "rich>=13.0",
    "keyring>=23.13"
]

[project.scripts]
bondmcp-cli = "bondmcp_cli.cli:cli"
