# =============================================================================
# WORKFLOW: Security & Compliance
# PURPOSE: Advanced security scanning and vulnerability detection
# TRIGGERS: Push to main, PRs, weekly schedule
# MAINTAINER: Aurora Capital DevOps Team
# LAST UPDATED: 2025-09-07
# DOCUMENTATION: See .github/workflows/README.md
# =============================================================================

name: 02 - Security & Compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly Monday 2 AM

jobs:
  security-scan:
    name: Comprehensive Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true

  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      if: hashFiles('package.json') != ''
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      if: hashFiles('package.json') != ''
      run: npm ci
      
    - name: Run npm audit
      if: hashFiles('package.json') != ''
      run: npm audit --audit-level moderate || echo "Audit completed with warnings"
      
    - name: Setup Python
      if: hashFiles('requirements.txt') != ''
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      if: hashFiles('requirements.txt') != ''
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety
        
    - name: Run Python security check
      if: hashFiles('requirements.txt') != ''
      run: safety check || echo "Safety check completed with warnings"
