# =============================================================================
# WORKFLOW: Production Deployment
# PURPOSE: Automated deployment to production environment
# TRIGGERS: Push to main (after CI passes)
# MAINTAINER: Aurora Capital DevOps Team
# LAST UPDATED: 2025-09-07
# DOCUMENTATION: See .github/workflows/README.md
# =============================================================================

name: 03 - Production Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: []  # Add CI workflow as dependency
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure Git
      run: |
        git config --global user.name "Aurora Capital Deploy"
        git config --global user.email "info@auroracapital.nl"
        
    - name: Setup Node.js
      if: hashFiles('package.json') != ''
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      if: hashFiles('package.json') != ''
      run: npm ci
      
    - name: Build for production
      if: hashFiles('package.json') != ''
      run: npm run build
      
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production environment..."
        echo "Add your deployment commands here"
        echo "Examples:"
        echo "- Vercel: vercel --prod (for production) or vercel (for staging)"
        echo "- AWS: aws s3 sync dist/ s3://your-bucket/"
        echo "- Docker: docker build and push commands"
        
    - name: Health check
      run: |
        echo "🏥 Running health checks..."
        echo "Add health check commands here"
        echo "curl -f https://your-domain.com/health || exit 1"
