name: Auto Ready on Green

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-ready:
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled to prevent failures
    steps:
      - name: Disabled
        run: echo "Auto ready temporarily disabled"
