name: Static Site CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure Git
      run: |
        git config --global user.name "Aurora Capital CI"
        git config --global user.email "info@auroracapital.nl"
        
    - name: Build site
      run: echo "Add your build commands here"
      
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: echo "Add your deployment commands here"
