name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run Python tests
        run: pytest -v
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Run Node tests
        run: node --test tests/test_bondmcp_node.js
