name: Ensure PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  ensure-checklist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check for existing checklist
        id: check_checklist
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const body = pr.body || '';
            const hasChecklist = body.includes('## ✅ Readiness Checklist');
            
            core.setOutput('has_checklist', hasChecklist);
            core.setOutput('current_body', body);
            
            console.log(`PR #${context.issue.number}: Checklist ${hasChecklist ? 'found' : 'missing'}`);

      - name: Add checklist if missing
        if: steps.check_checklist.outputs.has_checklist == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const currentBody = `${{ steps.check_checklist.outputs.current_body }}`;
            
            const checklist = `

## ✅ Readiness Checklist

Before this PR can be merged, please ensure all items are completed:

### Code Quality
- [ ] Code follows project coding standards and conventions
- [ ] All new code has appropriate test coverage
- [ ] Existing tests continue to pass
- [ ] No new linting errors or warnings introduced

### Documentation
- [ ] Public APIs are documented with clear examples
- [ ] README and relevant documentation updated if needed
- [ ] Changelog updated for user-facing changes

### Contract Changes (if applicable)
- [ ] OpenAPI specification updated and validated
- [ ] SDK generation tested and working
- [ ] Breaking changes documented with migration guide
- [ ] Backward compatibility considered and maintained where possible

### Testing & Validation
- [ ] Manual testing completed for new functionality
- [ ] Integration tests pass in CI/CD pipeline
- [ ] Performance impact assessed (if applicable)
- [ ] Security implications reviewed

### Deployment Readiness
- [ ] Configuration changes documented
- [ ] Database migrations tested (if applicable)
- [ ] Deployment steps verified
- [ ] Rollback plan considered

---

*This checklist is automatically managed. Please check off completed items manually.*`;

            const newBody = currentBody + checklist;
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: newBody,
            });
            
            console.log(`✅ Added readiness checklist to PR #${context.issue.number}`);

      - name: Add checklist comment
        if: steps.check_checklist.outputs.has_checklist == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🤖 **Readiness Checklist Added**

I've added a readiness checklist to this PR. Please review and check off the completed items to help ensure a smooth review and merge process.

The checklist covers:
- Code quality and testing
- Documentation updates
- Contract changes (if applicable)
- Testing & validation
- Deployment readiness

Once all items are completed and CI checks pass, this PR will be ready for review! 🚀`
            });

      - name: Summary
        run: |
          if [ "${{ steps.check_checklist.outputs.has_checklist }}" == "true" ]; then
            echo "✅ PR already has readiness checklist"
          else
            echo "📝 Added readiness checklist to PR"
          fi
          
          echo "PR #${{ github.event.pull_request.number }} checklist status updated"