name: SEObot Blog Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-seobot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run SEObot sync
        env:
          SEOBOT_API_KEY: ${{ secrets.SEOBOT_API_KEY }}
        run: node scripts/sync-seobot-to-blog.js

      - name: Check for changes
        id: changes
        run: |
          git config user.name "BondMCP Bot"
          git config user.email "bot@bondmcp.com"
          
          if [[ -n $(git status --porcelain blog/) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "📝 New blog articles detected"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "✓ No new articles"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add blog/
          git commit -m "chore: sync blog articles from SEObot [skip ci]"
          git push origin main

      - name: Create summary
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          echo "### 📚 SEObot Blog Sync Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**New articles added:**" >> $GITHUB_STEP_SUMMARY
          git diff HEAD~1 --name-only blog/ | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 [View commit](https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD))" >> $GITHUB_STEP_SUMMARY
